import json
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import os
import sys

# Use config for all paths
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "data_pipeline"))
from data_pipeline.config import CLASSIFIED_REPORTS_FILE, HINGLISH_FILE

# Import the new multilingual embedding function
sys.path.insert(0, os.path.dirname(__file__))
from llm_client import embed_texts

def train_raw_text_classifier():
    """
    Method 3: Semantic Text Classifier.
    Trains a separate Logistic Regression model directly on the raw text using 
    a dense Multilingual Embedding Model (sentence-transformers).
    This acts as a safety net: it mathematically understands meaning across Hindi, English, etc.
    """
    json_file = CLASSIFIED_REPORTS_FILE
    csv_file = HINGLISH_FILE
    
    if not os.path.exists(json_file) or not os.path.exists(csv_file):
        print("Error: Missing data files.")
        return
        
    print("Loading data for Method 3 (Semantic Text Classification)...")
    
    # Load JSON labels
    with open(json_file, 'r', encoding='utf-8') as f:
        json_data = json.load(f)
    df_labels = pd.DataFrame(json_data)[['report_id', 'sif_potential']]
    
    # Load original text
    df_text = pd.read_csv(csv_file)[['report_id', 'narrative']]
    
    # Merge them
    df = pd.merge(df_text, df_labels, on='report_id')
    
    # 1. Feature: The raw, unstructured text
    X_text = df['narrative'].tolist()
    
    # Target: The weak labels generated by Method 1
    y = df['sif_potential'].astype(int)
    
    print("Vectorizing multilingual text using sentence-transformers (384-dim)...")
    # 2. Convert text to numerical vectors capturing true semantic meaning
    X_vectors = embed_texts(X_text)
    
    # Split into train/test
    X_train, X_test, y_train, y_test = train_test_split(X_vectors, y, test_size=0.2, random_state=42)
    
    # 3. Train the Semantic Model
    print("Training Logistic Regression Model on Embedding Vectors...")
    model = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)
    model.fit(X_train, y_train)
    
    # 4. Evaluate
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    
    print(f"\nMethod 3 Accuracy (Embeddings): {acc * 100:.2f}%\n")
    print("Note: Unlike TF-IDF, embeddings learn meaning. 'Bina helmet' and 'No hardhat' map to similar vectors.")

if __name__ == "__main__":
    train_raw_text_classifier()
