import json
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import os

def train_raw_text_classifier():
    """
    Method 3: Raw-Text Classifier.
    Trains a completely separate model directly on the raw, unstructured Hinglish text.
    This acts as a safety net: it does not rely on the JSON extraction from Step 2.
    """
    json_file = r"C:\Users\rithy\OneDrive\Desktop\SIH_2026\sih_2026\data\processed\classified_reports.json"
    csv_file = r"C:\Users\rithy\OneDrive\Desktop\SIH_2026\sih_2026\data\processed\hinglish_synthetic.csv"
    
    if not os.path.exists(json_file) or not os.path.exists(csv_file):
        print("Error: Missing data files.")
        return
        
    print("Loading data for Method 3 (Raw-Text Classification)...")
    
    # Load JSON labels
    with open(json_file, 'r', encoding='utf-8') as f:
        json_data = json.load(f)
    df_labels = pd.DataFrame(json_data)[['report_id', 'sif_potential']]
    
    # Load original text
    df_text = pd.read_csv(csv_file)[['report_id', 'narrative']]
    
    # Merge them
    df = pd.merge(df_text, df_labels, on='report_id')
    
    # 1. Feature: The raw, unstructured Hinglish text
    X_text = df['narrative']
    
    # Target: The weak labels generated by Method 1
    y = df['sif_potential'].astype(int)
    
    print("Vectorizing Hinglish text using TF-IDF...")
    # 2. Convert text to numerical vectors (TF-IDF captures important keywords like 'bina', 'missing', 'fall')
    vectorizer = TfidfVectorizer(max_features=500, stop_words='english')
    X_vectors = vectorizer.fit_transform(X_text)
    
    # Split into train/test
    X_train, X_test, y_train, y_test = train_test_split(X_vectors, y, test_size=0.2, random_state=42)
    
    # 3. Train the Raw-Text Model
    print("Training Logistic Regression Model on Raw Text...")
    model = LogisticRegression(class_weight='balanced', random_state=42)
    model.fit(X_train, y_train)
    
    # 4. Evaluate
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    
    print(f"\nMethod 3 Accuracy: {acc * 100:.2f}%\n")
    
    # 5. Show Top Keywords the model learned indicating a SIF
    print("Top Hinglish/English keywords the model associates with SIF Potential:")
    feature_names = vectorizer.get_feature_names_out()
    coefficients = model.coef_[0]
    
    # Zip names and coefficients, then sort by highest coefficient
    keyword_weights = list(zip(feature_names, coefficients))
    keyword_weights.sort(key=lambda x: x[1], reverse=True)
    
    for word, weight in keyword_weights[:5]:
        print(f"- '{word}' (Impact Weight: {weight:.2f})")

if __name__ == "__main__":
    train_raw_text_classifier()
